version: 3.7

services:
  app:
    build: .
    container_name: desafio_hub
    restart: always
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
  database:
    image: postgres
    container_name: database_postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=desafio
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local